# Generated by Django 3.0.11 on 2020-11-22 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='desc',
            field=models.CharField(max_length=255, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='store',
            name='desc',
            field=models.CharField(max_length=255, verbose_name='Описание'),
        ),
    ]
