# Generated by Django 3.0.11 on 2020-11-24 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_category_parent_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='parent_category',
        ),
    ]
