# Generated by Django 3.0.11 on 2020-11-26 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_category_parent_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='slug',
            field=models.SlugField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='picture',
            field=models.ImageField(blank=True, default='products_pic/no-image.jpg', upload_to='products_pic/', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='store',
            name='avatar',
            field=models.ImageField(blank=True, default='store_avatars/no-image.jpg', upload_to='store_avatars/', verbose_name='Аватар'),
        ),
    ]
