# Generated by Django 3.0.11 on 2020-12-07 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20201207_2010'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'permissions': (('view_orders_page', 'Can view the orders page'), ('take_orders', 'Can take orders')), 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
    ]
