# Generated by Django 3.0.11 on 2020-12-09 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_applicationform'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationform',
            name='name',
            field=models.CharField(default='Елена', max_length=255, verbose_name='ИФО'),
        ),
    ]
