# Generated by Django 3.0.11 on 2020-12-09 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_applicationform_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicationform',
            options={'permissions': (('accept_app', 'Can accept applications'),), 'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.AlterField(
            model_name='applicationform',
            name='name',
            field=models.CharField(max_length=255, verbose_name='ИФО'),
        ),
    ]
