# Generated by Django 3.0.11 on 2020-12-09 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20201209_2125'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicationform',
            options={'permissions': (('view_app_page', 'Can view the applications page'), ('accept_app', 'Can accept applications')), 'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
    ]
