# Generated by Django 3.0.11 on 2020-12-09 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20201209_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationform',
            name='status',
            field=models.CharField(choices=[('В ожидании', 'Заявка в ожидании'), ('Принято', 'Заявка принята'), ('Отказано', 'Заявка отказана')], default='В ожидании', max_length=16, verbose_name='Статус'),
        ),
    ]
